package api

import (
	"io"
	"log/slog"
	"net/http"

	"rekenraam/backend/internal/app"
)

type healthResponse struct {
	Status string `json:"status"`
}

func RegisterRoutes(mux *http.ServeMux, logger *slog.Logger, setupService *app.SetupService) {
	RegisterRoutesWithAuth(mux, logger, Services{Setup: setupService}, HandlerOptions{})
}

func RegisterRoutesWithAuth(mux *http.ServeMux, logger *slog.Logger, services Services, options HandlerOptions) {
	if logger == nil {
		logger = slog.New(slog.NewTextHandler(io.Discard, nil))
	}

	mux.HandleFunc("GET /healthz", healthz)
	mux.HandleFunc("GET /api/v1/health", health)
	mux.HandleFunc("GET /api/v1/setup/status", setupStatus(logger, services.Setup))
	mux.HandleFunc("POST /api/v1/setup/owner", requireSameOrigin(options, createOwner(logger, services.Setup, options)))

	if services.Auth == nil {
		return
	}

	mux.HandleFunc("GET /api/v1/auth/session", sessionStatus(logger, services.Auth))
	mux.HandleFunc("POST /api/v1/auth/login", requireSameOrigin(options, login(logger, services.Auth, options)))
	mux.HandleFunc("POST /api/v1/auth/logout", logout(logger, services.Auth, options))
	mux.HandleFunc("GET /api/v1/settings/preferences", userPreferences(logger, services.Auth, services.Settings))
	mux.HandleFunc("PUT /api/v1/settings/preferences", saveUserPreferences(logger, services.Auth, services.Settings, options))
	mux.HandleFunc("GET /api/v1/settings/currencies/page-data", currencySettingsPageData(logger, services.Auth, services.Settings, services.Book, services.Currency, services.Pricing))
	mux.HandleFunc("GET /api/v1/books/current", currentBook(logger, services.Auth, services.Book))
	mux.HandleFunc("POST /api/v1/setup/book", createBook(logger, services.Auth, services.Book, options))
	mux.HandleFunc("GET /api/v1/currencies/catalog", currencyCatalog(logger, services.Auth, services.Currency))
	mux.HandleFunc("GET /api/v1/currencies", listCurrencies(logger, services.Auth, services.Currency))
	mux.HandleFunc("POST /api/v1/currencies", createCurrency(logger, services.Auth, services.Currency, options))
	mux.HandleFunc("POST /api/v1/currencies/{commodity_id}/default", setDefaultCurrency(logger, services.Auth, services.Currency, options))
	mux.HandleFunc("POST /api/v1/setup/currencies", completeCurrencySetup(logger, services.Auth, services.Currency, options))
	mux.HandleFunc("GET /api/v1/institutions", listInstitutions(logger, services.Auth, services.Institution))
	mux.HandleFunc("POST /api/v1/institutions", createInstitution(logger, services.Auth, services.Institution, options))
	mux.HandleFunc("GET /api/v1/institutions/{institution_id}", readInstitution(logger, services.Auth, services.Institution))
	mux.HandleFunc("PATCH /api/v1/institutions/{institution_id}", updateInstitution(logger, services.Auth, services.Institution, options))
	mux.HandleFunc("DELETE /api/v1/institutions/{institution_id}", deleteInstitution(logger, services.Auth, services.Institution, options))
	mux.HandleFunc("POST /api/v1/institutions/{institution_id}/archive", archiveInstitution(logger, services.Auth, services.Institution, options))
	mux.HandleFunc("POST /api/v1/institutions/{institution_id}/restore", restoreInstitution(logger, services.Auth, services.Institution, options))
	mux.HandleFunc("GET /api/v1/institutions/{institution_id}/versions", listInstitutionVersions(logger, services.Auth, services.Institution))
	mux.HandleFunc("GET /api/v1/accounts", listAccounts(logger, services.Auth, services.Account))
	mux.HandleFunc("POST /api/v1/accounts", createAccount(logger, services.Auth, services.Account, options))
	mux.HandleFunc("GET /api/v1/accounts/{account_id}", readAccount(logger, services.Auth, services.Account))
	mux.HandleFunc("GET /api/v1/accounts/{account_id}/register", accountRegister(logger, services.Auth, services.Transaction))
	mux.HandleFunc("PATCH /api/v1/accounts/{account_id}", updateAccount(logger, services.Auth, services.Account, options))
	mux.HandleFunc("DELETE /api/v1/accounts/{account_id}", deleteAccount(logger, services.Auth, services.Account, options))
	mux.HandleFunc("POST /api/v1/accounts/{account_id}/close", closeAccount(logger, services.Auth, services.Account, options))
	mux.HandleFunc("POST /api/v1/accounts/{account_id}/reopen", reopenAccount(logger, services.Auth, services.Account, options))
	mux.HandleFunc("POST /api/v1/accounts/{account_id}/archive", archiveAccount(logger, services.Auth, services.Account, options))
	mux.HandleFunc("POST /api/v1/accounts/{account_id}/restore", restoreAccount(logger, services.Auth, services.Account, options))
	mux.HandleFunc("GET /api/v1/accounts/{account_id}/versions", listAccountVersions(logger, services.Auth, services.Account))
	mux.HandleFunc("POST /api/v1/setup/system-accounts", completeSystemAccountsSetup(logger, services.Auth, services.Account, options))
	mux.HandleFunc("GET /api/v1/tags", listTags(logger, services.Auth, services.Tag))
	mux.HandleFunc("POST /api/v1/tags", createTag(logger, services.Auth, services.Tag, options))
	mux.HandleFunc("GET /api/v1/tags/{tag_id}", readTag(logger, services.Auth, services.Tag))
	mux.HandleFunc("PATCH /api/v1/tags/{tag_id}", updateTag(logger, services.Auth, services.Tag, options))
	mux.HandleFunc("POST /api/v1/tags/{tag_id}/archive", archiveTag(logger, services.Auth, services.Tag, options))
	mux.HandleFunc("POST /api/v1/tags/{tag_id}/restore", restoreTag(logger, services.Auth, services.Tag, options))
	mux.HandleFunc("GET /api/v1/categories", listCategories(logger, services.Auth, services.Category))
	mux.HandleFunc("POST /api/v1/categories", createCategory(logger, services.Auth, services.Category, options))
	mux.HandleFunc("GET /api/v1/categories/{category_id}", readCategory(logger, services.Auth, services.Category))
	mux.HandleFunc("PATCH /api/v1/categories/{category_id}", updateCategory(logger, services.Auth, services.Category, options))
	mux.HandleFunc("POST /api/v1/categories/{category_id}/disable", disableCategory(logger, services.Auth, services.Category, options))
	mux.HandleFunc("POST /api/v1/categories/{category_id}/restore", restoreCategory(logger, services.Auth, services.Category, options))
	mux.HandleFunc("DELETE /api/v1/categories/{category_id}", deleteCategory(logger, services.Auth, services.Category, options))
	mux.HandleFunc("POST /api/v1/setup/categories", completeCategoriesSetup(logger, services.Auth, services.Category, options))
	mux.HandleFunc("GET /api/v1/payees", listPayees(logger, services.Auth, services.Payee))
	mux.HandleFunc("POST /api/v1/payees", createPayee(logger, services.Auth, services.Payee, options))
	mux.HandleFunc("GET /api/v1/payees/{payee_id}", readPayee(logger, services.Auth, services.Payee))
	mux.HandleFunc("PATCH /api/v1/payees/{payee_id}", updatePayee(logger, services.Auth, services.Payee, options))
	mux.HandleFunc("POST /api/v1/payees/{payee_id}/archive", archivePayee(logger, services.Auth, services.Payee, options))
	mux.HandleFunc("POST /api/v1/payees/{payee_id}/restore", restorePayee(logger, services.Auth, services.Payee, options))
	mux.HandleFunc("GET /api/v1/ledger/account-balances", accountBalances(logger, services.Auth, services.Transaction))
	mux.HandleFunc("GET /api/v1/ledger/category-totals", categoryTotals(logger, services.Auth, services.Transaction))
	mux.HandleFunc("GET /api/v1/ledger/net-worth", netWorth(logger, services.Auth, services.Transaction))
	mux.HandleFunc("GET /api/v1/reports/net-worth", netWorthSeries(logger, services.Auth, services.Transaction))
	mux.HandleFunc("GET /api/v1/reports/cashflow", cashflowReport(logger, services.Auth, services.Transaction))
	mux.HandleFunc("GET /api/v1/reports/spending", spendingReport(logger, services.Auth, services.Transaction))
	mux.HandleFunc("GET /api/v1/transactions", listTransactions(logger, services.Auth, services.Transaction))
	mux.HandleFunc("GET /api/v1/transactions/deleted", listDeletedTransactions(logger, services.Auth, services.Transaction))
	mux.HandleFunc("POST /api/v1/transactions", createTransaction(logger, services.Auth, services.Transaction, options))
	mux.HandleFunc("GET /api/v1/transactions/{transaction_id}", readTransaction(logger, services.Auth, services.Transaction))
	mux.HandleFunc("PATCH /api/v1/transactions/{transaction_id}", updateTransaction(logger, services.Auth, services.Transaction, options))
	mux.HandleFunc("POST /api/v1/transactions/{transaction_id}/post", postTransaction(logger, services.Auth, services.Transaction, options))
	mux.HandleFunc("POST /api/v1/transactions/{transaction_id}/void", voidTransaction(logger, services.Auth, services.Transaction, options))
	mux.HandleFunc("POST /api/v1/transactions/{transaction_id}/unvoid", unvoidTransaction(logger, services.Auth, services.Transaction, options))
	mux.HandleFunc("POST /api/v1/transactions/{transaction_id}/soft-delete", softDeleteTransaction(logger, services.Auth, services.Transaction, options))
	mux.HandleFunc("POST /api/v1/transactions/{transaction_id}/restore", restoreTransaction(logger, services.Auth, services.Transaction, options))
	mux.HandleFunc("POST /api/v1/transactions/{transaction_id}/correct", correctTransaction(logger, services.Auth, services.Transaction, options))
	mux.HandleFunc("DELETE /api/v1/transactions/{transaction_id}", deleteDraftTransaction(logger, services.Auth, services.Transaction, options))
	mux.HandleFunc("POST /api/v1/transactions/{transaction_id}/approve", approveTransaction(logger, services.Auth, services.Transaction, options))
	mux.HandleFunc("POST /api/v1/transactions/{transaction_id}/move", moveTransaction(logger, services.Auth, services.Transaction, options))
	mux.HandleFunc("POST /api/v1/accounts/{account_id}/postings/{posting_line_id}/move", movePosting(logger, services.Auth, services.Transaction, options))
	mux.HandleFunc("POST /api/v1/transactions/reconciliation-impact", createReconciliationImpact(logger, services.Auth, services.Transaction))
	mux.HandleFunc("POST /api/v1/transactions/{transaction_id}/reconciliation-impact", updateReconciliationImpact(logger, services.Auth, services.Transaction))
	mux.HandleFunc("POST /api/v1/accounts/{account_id}/reconciliations/start", startReconciliation(logger, services.Auth, services.Transaction, options))
	mux.HandleFunc("GET /api/v1/reconciliations/{reconciliation_id}", readReconciliation(logger, services.Auth, services.Transaction))
	mux.HandleFunc("PATCH /api/v1/reconciliations/{reconciliation_id}", updateReconciliationSelection(logger, services.Auth, services.Transaction, options))
	mux.HandleFunc("POST /api/v1/reconciliations/{reconciliation_id}/preview", previewReconciliation(logger, services.Auth, services.Transaction, options))
	mux.HandleFunc("POST /api/v1/reconciliations/{reconciliation_id}/finish", finishReconciliation(logger, services.Auth, services.Transaction, options))
	mux.HandleFunc("POST /api/v1/reconciliations/{reconciliation_id}/void", voidReconciliation(logger, services.Auth, services.Transaction, options))
	mux.HandleFunc("GET /api/v1/accounts/{account_id}/reconciliation-checkpoints", listReconciliationCheckpoints(logger, services.Auth, services.Transaction))
	mux.HandleFunc("POST /api/v1/reconciliation-checkpoints/{checkpoint_id}/void", voidReconciliationCheckpoint(logger, services.Auth, services.Transaction, options))
	mux.HandleFunc("POST /api/v1/accounts/{account_id}/postings/reconciliation-status", changePostingReconciliationStatus(logger, services.Auth, services.Transaction, options))
	mux.HandleFunc("GET /api/v1/pricing/sources", listMarketDataSources(logger, services.Auth, services.Pricing))
	mux.HandleFunc("GET /api/v1/pricing/prices", listPrices(logger, services.Auth, services.Pricing))
	mux.HandleFunc("POST /api/v1/pricing/prices", createPrice(logger, services.Auth, services.Pricing, options))
	mux.HandleFunc("POST /api/v1/pricing/prices/{price_id}/void", voidPrice(logger, services.Auth, services.Pricing, options))
	mux.HandleFunc("GET /api/v1/pricing/policy", getPricingPolicy(logger, services.Auth, services.Pricing))
	mux.HandleFunc("PUT /api/v1/pricing/policy", savePricingPolicy(logger, services.Auth, services.Pricing, options))
	mux.HandleFunc("GET /api/v1/pricing/source-assignments", listPricingSourceAssignments(logger, services.Auth, services.Pricing))
	mux.HandleFunc("POST /api/v1/pricing/source-assignments", savePricingSourceAssignment(logger, services.Auth, services.Pricing, options, false))
	mux.HandleFunc("PATCH /api/v1/pricing/source-assignments/{assignment_id}", savePricingSourceAssignment(logger, services.Auth, services.Pricing, options, true))
	mux.HandleFunc("POST /api/v1/pricing/refresh/run", runPricingRefresh(logger, services.Auth, services.Pricing, options))
	mux.HandleFunc("GET /api/v1/pricing/refresh/runs", listPricingRefreshRuns(logger, services.Auth, services.Pricing))
	mux.HandleFunc("GET /api/v1/pricing/source-health", pricingSourceHealth(logger, services.Auth, services.Pricing))
	mux.HandleFunc("POST /api/v1/pricing/background-work/{work_id}/retry", retryPricingBackgroundWork(logger, services.Auth, services.Pricing, options))
	mux.HandleFunc("GET /api/v1/investments/search", searchInvestments(logger, services.Auth, services.Investment))
	mux.HandleFunc("GET /api/v1/investments/instruments", listInvestmentInstruments(logger, services.Auth, services.Investment))
	mux.HandleFunc("POST /api/v1/investments/instruments", createInvestmentInstrument(logger, services.Auth, services.Investment, options))
	mux.HandleFunc("GET /api/v1/investments/instruments/{instrument_id}", readInvestmentInstrument(logger, services.Auth, services.Investment))
	mux.HandleFunc("PATCH /api/v1/investments/instruments/{instrument_id}", updateInvestmentInstrument(logger, services.Auth, services.Investment, options))
	mux.HandleFunc("POST /api/v1/investments/holding-accounts", createHoldingAccount(logger, services.Auth, services.Investment, options))
	mux.HandleFunc("GET /api/v1/investments/positions", listInvestmentPositions(logger, services.Auth, services.Investment))
	mux.HandleFunc("GET /api/v1/investments/lots", listInvestmentLots(logger, services.Auth, services.Investment))
	mux.HandleFunc("GET /api/v1/investments/cost-basis-profiles", listCostBasisProfiles(logger, services.Auth, services.Investment))
	mux.HandleFunc("POST /api/v1/investments/cost-basis-profiles", saveCostBasisProfile(logger, services.Auth, services.Investment, options, false))
	mux.HandleFunc("PATCH /api/v1/investments/cost-basis-profiles/{profile_id}", saveCostBasisProfile(logger, services.Auth, services.Investment, options, true))
	mux.HandleFunc("GET /api/v1/investments/dividend-defaults", listDividendDefaults(logger, services.Auth, services.Investment))
	mux.HandleFunc("POST /api/v1/investments/dividend-defaults", saveDividendDefault(logger, services.Auth, services.Investment, options, false))
	mux.HandleFunc("PATCH /api/v1/investments/dividend-defaults/{default_id}", saveDividendDefault(logger, services.Auth, services.Investment, options, true))
	mux.HandleFunc("POST /api/v1/investments/buy", buyInvestment(logger, services.Auth, services.Investment, options))
	mux.HandleFunc("POST /api/v1/investments/sell", sellInvestment(logger, services.Auth, services.Investment, options))
	mux.HandleFunc("POST /api/v1/investments/sell/preview", sellPreviewInvestment(logger, services.Auth, services.Investment))
	mux.HandleFunc("POST /api/v1/investments/dividend", createDividend(logger, services.Auth, services.Investment, options))
	mux.HandleFunc("POST /api/v1/investments/reinvested-dividend", createReinvestedDividend(logger, services.Auth, services.Investment, options))
	mux.HandleFunc("GET /api/v1/investments/events", listInvestmentEvents(logger, services.Auth, services.Investment))
	mux.HandleFunc("GET /api/v1/investments/event-suggestions", listInvestmentEventSuggestions(logger, services.Auth, services.Investment))
	mux.HandleFunc("POST /api/v1/investments/event-suggestions/{suggestion_id}/accept", acceptInvestmentEventSuggestion(logger, services.Auth, services.Investment, options))
	mux.HandleFunc("POST /api/v1/investments/event-suggestions/{suggestion_id}/ignore", ignoreInvestmentEventSuggestion(logger, services.Auth, services.Investment, options))
	mux.HandleFunc("GET /api/v1/investments/automation-rules", listInvestmentAutomationRules(logger, services.Auth, services.Investment))
	mux.HandleFunc("PUT /api/v1/investments/automation-rules", saveInvestmentAutomationRules(logger, services.Auth, services.Investment, options))
	mux.HandleFunc("GET /api/v1/investments/gains", listInvestmentGains(logger, services.Auth, services.Investment))
	mux.HandleFunc("POST /api/v1/imports", startImport(logger, services.Auth, services.Import, options))
	mux.HandleFunc("GET /api/v1/imports", listImportBatches(logger, services.Auth, services.Import))
	mux.HandleFunc("GET /api/v1/imports/{batch_id}", getImportBatch(logger, services.Auth, services.Import))
	mux.HandleFunc("PATCH /api/v1/imports/{batch_id}", patchImportBatch(logger, services.Auth, services.Import, options))
	mux.HandleFunc("POST /api/v1/imports/{batch_id}/preview-commit", previewCommitImportBatch(logger, services.Auth, services.Import))
	mux.HandleFunc("POST /api/v1/imports/{batch_id}/commit", commitImportBatch(logger, services.Auth, services.Import, options))
	mux.HandleFunc("POST /api/v1/imports/{batch_id}/discard", discardImportBatch(logger, services.Auth, services.Import, options))

	if services.ImportConnection != nil {
		mux.HandleFunc("GET /api/v1/import-connections", listImportConnections(logger, services.Auth, services.ImportConnection))
		mux.HandleFunc("POST /api/v1/import-connections", createImportConnection(logger, services.Auth, services.ImportConnection, options))
		mux.HandleFunc("PATCH /api/v1/import-connections/{connection_id}", updateImportConnection(logger, services.Auth, services.ImportConnection, options))
		mux.HandleFunc("DELETE /api/v1/import-connections/{connection_id}", deleteImportConnection(logger, services.Auth, services.ImportConnection, options))
		mux.HandleFunc("POST /api/v1/import-connections/{connection_id}/refresh", refreshImportConnection(logger, services.Auth, services.Import, options))
	}
}

func healthz(w http.ResponseWriter, _ *http.Request) {
	w.WriteHeader(http.StatusNoContent)
}

func health(w http.ResponseWriter, _ *http.Request) {
	writeJSON(w, http.StatusOK, healthResponse{Status: "ok"})
}
