/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health check */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Health response */
                200: {
                    headers: {
                        "X-Request-ID": components["headers"]["XRequestID"];
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["HealthResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/setup/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read coarse setup progress */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Setup progress */
                200: {
                    headers: {
                        "X-Request-ID": components["headers"]["XRequestID"];
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SetupStatusResponse"];
                    };
                };
                /** @description Internal server error */
                500: {
                    headers: {
                        "X-Request-ID": components["headers"]["XRequestID"];
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/setup/owner": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create the single owner account during first-run setup */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["CreateOwnerRequest"];
                };
            };
            responses: {
                /** @description Owner created and setup advanced to the next step */
                201: {
                    headers: {
                        "X-Request-ID": components["headers"]["XRequestID"];
                        /** @description Browser session cookie for the newly created owner. */
                        "Set-Cookie"?: string;
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["CreateOwnerResponse"];
                    };
                };
                /** @description Invalid request body or validation failure */
                400: {
                    headers: {
                        "X-Request-ID": components["headers"]["XRequestID"];
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description Owner setup is already complete */
                409: {
                    headers: {
                        "X-Request-ID": components["headers"]["XRequestID"];
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description Internal server error */
                500: {
                    headers: {
                        "X-Request-ID": components["headers"]["XRequestID"];
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        HealthResponse: {
            /** @example ok */
            status: string;
        };
        SetupStep: {
            /** @enum {string} */
            key: "owner" | "book" | "currencies" | "system_accounts" | "categories";
            /** @enum {string} */
            status: "pending" | "completed";
        };
        SetupStatusResponse: {
            completed: boolean;
            /** @enum {string} */
            current_step?: "owner" | "book" | "currencies" | "system_accounts" | "categories";
            steps: components["schemas"]["SetupStep"][];
        };
        CreateOwnerRequest: {
            /** @description Username for the single owner account. */
            username: string;
            /** @description Password for the single owner account. */
            password: string;
        };
        OwnerResponse: {
            id: number;
            username: string;
        };
        CreateOwnerResponse: {
            owner: components["schemas"]["OwnerResponse"];
            setup: components["schemas"]["SetupStatusResponse"];
        };
        ErrorBody: {
            /** @enum {string} */
            code: "VALIDATION_FAILED" | "UNAUTHENTICATED" | "FORBIDDEN" | "NOT_FOUND" | "CONFLICT" | "CSRF_INVALID" | "RATE_LIMITED" | "RESOURCE_BUSY" | "SETUP_REQUIRED" | "SETUP_ALREADY_COMPLETE" | "INTERNAL_ERROR";
            message: string;
        };
        ErrorResponse: {
            error: components["schemas"]["ErrorBody"];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: {
        /** @description Server-generated request identifier for this response. */
        XRequestID: string;
    };
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
