/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health check */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Health response */
                200: {
                    headers: {
                        "X-Request-ID": components["headers"]["XRequestID"];
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["HealthResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/session": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read the current browser auth session */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Current session status */
                200: {
                    headers: {
                        "X-Request-ID": components["headers"]["XRequestID"];
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["AuthSessionResponse"];
                    };
                };
                /** @description Internal server error */
                500: {
                    headers: {
                        "X-Request-ID": components["headers"]["XRequestID"];
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create a browser session for the owner account */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["LoginRequest"];
                };
            };
            responses: {
                /** @description Owner logged in */
                200: {
                    headers: {
                        "X-Request-ID": components["headers"]["XRequestID"];
                        /** @description Browser session cookie for the authenticated owner. */
                        "Set-Cookie"?: string;
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["LoginResponse"];
                    };
                };
                /** @description Invalid request body or validation failure */
                400: {
                    headers: {
                        "X-Request-ID": components["headers"]["XRequestID"];
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description Invalid username or password */
                401: {
                    headers: {
                        "X-Request-ID": components["headers"]["XRequestID"];
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description Origin validation failed */
                403: {
                    headers: {
                        "X-Request-ID": components["headers"]["XRequestID"];
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description Owner setup is required before login */
                409: {
                    headers: {
                        "X-Request-ID": components["headers"]["XRequestID"];
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description Too many failed login attempts */
                429: {
                    headers: {
                        "X-Request-ID": components["headers"]["XRequestID"];
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description Internal server error */
                500: {
                    headers: {
                        "X-Request-ID": components["headers"]["XRequestID"];
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Revoke the current browser session */
        post: {
            parameters: {
                query?: never;
                header: {
                    /** @description Session-bound CSRF token for authenticated mutating requests. */
                    "X-CSRF-Token": string;
                };
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Session revoked */
                204: {
                    headers: {
                        "X-Request-ID": components["headers"]["XRequestID"];
                        /** @description Clearing browser session cookie. */
                        "Set-Cookie"?: string;
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Authentication is required */
                401: {
                    headers: {
                        "X-Request-ID": components["headers"]["XRequestID"];
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description Origin or CSRF validation failed */
                403: {
                    headers: {
                        "X-Request-ID": components["headers"]["XRequestID"];
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description Internal server error */
                500: {
                    headers: {
                        "X-Request-ID": components["headers"]["XRequestID"];
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/setup/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read coarse setup progress */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Setup progress */
                200: {
                    headers: {
                        "X-Request-ID": components["headers"]["XRequestID"];
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SetupStatusResponse"];
                    };
                };
                /** @description Internal server error */
                500: {
                    headers: {
                        "X-Request-ID": components["headers"]["XRequestID"];
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/setup/owner": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create the single owner account during first-run setup */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["CreateOwnerRequest"];
                };
            };
            responses: {
                /** @description Owner created and setup advanced to the next step */
                201: {
                    headers: {
                        "X-Request-ID": components["headers"]["XRequestID"];
                        /** @description Browser session cookie for the newly created owner. */
                        "Set-Cookie"?: string;
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["CreateOwnerResponse"];
                    };
                };
                /** @description Invalid request body or validation failure */
                400: {
                    headers: {
                        "X-Request-ID": components["headers"]["XRequestID"];
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description Origin validation failed */
                403: {
                    headers: {
                        "X-Request-ID": components["headers"]["XRequestID"];
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description Owner setup is already complete */
                409: {
                    headers: {
                        "X-Request-ID": components["headers"]["XRequestID"];
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description Internal server error */
                500: {
                    headers: {
                        "X-Request-ID": components["headers"]["XRequestID"];
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/setup/book": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create the single owner book during setup */
        post: {
            parameters: {
                query?: never;
                header: {
                    /** @description Session-bound CSRF token for authenticated mutating requests. */
                    "X-CSRF-Token": string;
                };
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["CreateBookRequest"];
                };
            };
            responses: {
                /** @description Book created and setup advanced to the next step */
                201: {
                    headers: {
                        "X-Request-ID": components["headers"]["XRequestID"];
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["CreateBookResponse"];
                    };
                };
                /** @description Invalid request body or validation failure */
                400: {
                    headers: {
                        "X-Request-ID": components["headers"]["XRequestID"];
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description Authentication is required */
                401: {
                    headers: {
                        "X-Request-ID": components["headers"]["XRequestID"];
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description Origin or CSRF validation failed */
                403: {
                    headers: {
                        "X-Request-ID": components["headers"]["XRequestID"];
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description Book already exists */
                409: {
                    headers: {
                        "X-Request-ID": components["headers"]["XRequestID"];
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description Internal server error */
                500: {
                    headers: {
                        "X-Request-ID": components["headers"]["XRequestID"];
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/books/current": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read the current single owner book */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Current book */
                200: {
                    headers: {
                        "X-Request-ID": components["headers"]["XRequestID"];
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["BookResponse"];
                    };
                };
                /** @description Authentication is required */
                401: {
                    headers: {
                        "X-Request-ID": components["headers"]["XRequestID"];
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description Book not found */
                404: {
                    headers: {
                        "X-Request-ID": components["headers"]["XRequestID"];
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description Internal server error */
                500: {
                    headers: {
                        "X-Request-ID": components["headers"]["XRequestID"];
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        HealthResponse: {
            /** @example ok */
            status: string;
        };
        LoginRequest: {
            /** @description Username for the single owner account. */
            username: string;
            /** @description Password for the single owner account. */
            password: string;
        };
        SetupStep: {
            /** @enum {string} */
            key: "owner" | "book" | "currencies" | "system_accounts" | "categories";
            /** @enum {string} */
            status: "pending" | "completed";
        };
        SetupStatusResponse: {
            completed: boolean;
            /** @enum {string} */
            current_step?: "owner" | "book" | "currencies" | "system_accounts" | "categories";
            /** @enum {string} */
            install_state: "fresh" | "configured" | "recovery_required";
            implemented_steps: ("owner" | "book")[];
            /** @enum {string} */
            blocking_step?: "owner";
            steps: components["schemas"]["SetupStep"][];
        };
        CreateOwnerRequest: {
            /** @description Username for the single owner account. Must be 1–64 bytes, no control characters. */
            username: string;
            /** @description Password for the single owner account. Minimum 12 Unicode characters, maximum 1024 bytes. */
            password: string;
        };
        OwnerResponse: {
            id: number;
            username: string;
        };
        BookResponse: {
            /**
             * Format: int64
             * @description Current runtime always uses book id 1.
             */
            id: number;
            /** Format: int64 */
            owner_user_id: number;
            /** @description Stable internal code for the single owner book. */
            code: string;
            /** @description User-visible book name. */
            name: string;
            /** Format: int64 */
            base_currency_commodity_id?: number | null;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
        };
        CreateBookRequest: {
            /** @description Optional stable code. Defaults to personal. Lowercase letters, numbers, underscores, and hyphens only. */
            code?: string;
            /** @description User-visible book name. */
            name: string;
        };
        CreateBookResponse: {
            book: components["schemas"]["BookResponse"];
            setup: components["schemas"]["SetupStatusResponse"];
        };
        AuthSessionResponse: {
            authenticated: boolean;
            user?: components["schemas"]["OwnerResponse"];
            /** @description Session-bound CSRF token for authenticated mutating requests. */
            csrf_token?: string;
        };
        LoginResponse: {
            user: components["schemas"]["OwnerResponse"];
        };
        CreateOwnerResponse: {
            owner: components["schemas"]["OwnerResponse"];
            setup: components["schemas"]["SetupStatusResponse"];
        };
        ErrorBody: {
            /** @enum {string} */
            code: "VALIDATION_FAILED" | "UNAUTHENTICATED" | "FORBIDDEN" | "NOT_FOUND" | "CONFLICT" | "CSRF_INVALID" | "RATE_LIMITED" | "RESOURCE_BUSY" | "SETUP_REQUIRED" | "SETUP_ALREADY_COMPLETE" | "INTERNAL_ERROR";
            message: string;
        };
        ErrorResponse: {
            error: components["schemas"]["ErrorBody"];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: {
        /** @description Server-generated request identifier for this response. */
        XRequestID: string;
    };
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
