package app

// currencyCatalog is generated from ICU/CLDR currency data used during development.
// Keep durable records keyed by code; frontend locale formatting supplies translated labels.
var currencyCatalog = []CurrencyCatalogEntry{
	{Code: "AED", Symbol: "AED", EnglishName: "United Arab Emirates Dirham", StandardScale: 2, MaxQuantityScale: 6},
	{Code: "AFN", Symbol: "؋", EnglishName: "Afghan Afghani", StandardScale: 0, MaxQuantityScale: 6},
	{Code: "ALL", Symbol: "ALL", EnglishName: "Albanian Lek", StandardScale: 0, MaxQuantityScale: 6},
	{Code: "AMD", Symbol: "֏", EnglishName: "Armenian Dram", StandardScale: 2, MaxQuantityScale: 6},
	{Code: "ANG", Symbol: "ANG", EnglishName: "Netherlands Antillean Guilder", StandardScale: 2, MaxQuantityScale: 6},
	{Code: "AOA", Symbol: "Kz", EnglishName: "Angolan Kwanza", StandardScale: 2, MaxQuantityScale: 6},
	{Code: "ARS", Symbol: "$", EnglishName: "Argentine Peso", StandardScale: 2, MaxQuantityScale: 6},
	{Code: "AUD", Symbol: "$", EnglishName: "Australian Dollar", StandardScale: 2, MaxQuantityScale: 6},
	{Code: "AWG", Symbol: "AWG", EnglishName: "Aruban Florin", StandardScale: 2, MaxQuantityScale: 6},
	{Code: "AZN", Symbol: "₼", EnglishName: "Azerbaijani Manat", StandardScale: 2, MaxQuantityScale: 6},
	{Code: "BAM", Symbol: "KM", EnglishName: "Bosnia-Herzegovina Convertible Mark", StandardScale: 2, MaxQuantityScale: 6},
	{Code: "BBD", Symbol: "$", EnglishName: "Barbadian Dollar", StandardScale: 2, MaxQuantityScale: 6},
	{Code: "BDT", Symbol: "৳", EnglishName: "Bangladeshi Taka", StandardScale: 2, MaxQuantityScale: 6},
	{Code: "BGN", Symbol: "BGN", EnglishName: "Bulgarian Lev", StandardScale: 2, MaxQuantityScale: 6},
	{Code: "BHD", Symbol: "BHD", EnglishName: "Bahraini Dinar", StandardScale: 3, MaxQuantityScale: 6},
	{Code: "BIF", Symbol: "BIF", EnglishName: "Burundian Franc", StandardScale: 0, MaxQuantityScale: 6},
	{Code: "BMD", Symbol: "$", EnglishName: "Bermudan Dollar", StandardScale: 2, MaxQuantityScale: 6},
	{Code: "BND", Symbol: "$", EnglishName: "Brunei Dollar", StandardScale: 2, MaxQuantityScale: 6},
	{Code: "BOB", Symbol: "Bs", EnglishName: "Bolivian Boliviano", StandardScale: 2, MaxQuantityScale: 6},
	{Code: "BRL", Symbol: "R$", EnglishName: "Brazilian Real", StandardScale: 2, MaxQuantityScale: 6},
	{Code: "BSD", Symbol: "$", EnglishName: "Bahamian Dollar", StandardScale: 2, MaxQuantityScale: 6},
	{Code: "BTN", Symbol: "BTN", EnglishName: "Bhutanese Ngultrum", StandardScale: 2, MaxQuantityScale: 6},
	{Code: "BWP", Symbol: "P", EnglishName: "Botswanan Pula", StandardScale: 2, MaxQuantityScale: 6},
	{Code: "BYN", Symbol: "BYN", EnglishName: "Belarusian Ruble", StandardScale: 2, MaxQuantityScale: 6},
	{Code: "BZD", Symbol: "$", EnglishName: "Belize Dollar", StandardScale: 2, MaxQuantityScale: 6},
	{Code: "CAD", Symbol: "$", EnglishName: "Canadian Dollar", StandardScale: 2, MaxQuantityScale: 6},
	{Code: "CDF", Symbol: "CDF", EnglishName: "Congolese Franc", StandardScale: 2, MaxQuantityScale: 6},
	{Code: "CHF", Symbol: "CHF", EnglishName: "Swiss Franc", StandardScale: 2, MaxQuantityScale: 6},
	{Code: "CLP", Symbol: "$", EnglishName: "Chilean Peso", StandardScale: 0, MaxQuantityScale: 6},
	{Code: "CNY", Symbol: "¥", EnglishName: "Chinese Yuan", StandardScale: 2, MaxQuantityScale: 6},
	{Code: "COP", Symbol: "$", EnglishName: "Colombian Peso", StandardScale: 0, MaxQuantityScale: 6},
	{Code: "CRC", Symbol: "₡", EnglishName: "Costa Rican Colón", StandardScale: 2, MaxQuantityScale: 6},
	{Code: "CUC", Symbol: "$", EnglishName: "Cuban Convertible Peso", StandardScale: 2, MaxQuantityScale: 6},
	{Code: "CUP", Symbol: "$", EnglishName: "Cuban Peso", StandardScale: 2, MaxQuantityScale: 6},
	{Code: "CVE", Symbol: "CVE", EnglishName: "Cape Verdean Escudo", StandardScale: 2, MaxQuantityScale: 6},
	{Code: "CZK", Symbol: "Kč", EnglishName: "Czech Koruna", StandardScale: 2, MaxQuantityScale: 6},
	{Code: "DJF", Symbol: "DJF", EnglishName: "Djiboutian Franc", StandardScale: 0, MaxQuantityScale: 6},
	{Code: "DKK", Symbol: "kr", EnglishName: "Danish Krone", StandardScale: 2, MaxQuantityScale: 6},
	{Code: "DOP", Symbol: "$", EnglishName: "Dominican Peso", StandardScale: 2, MaxQuantityScale: 6},
	{Code: "DZD", Symbol: "DZD", EnglishName: "Algerian Dinar", StandardScale: 2, MaxQuantityScale: 6},
	{Code: "EGP", Symbol: "E£", EnglishName: "Egyptian Pound", StandardScale: 2, MaxQuantityScale: 6},
	{Code: "ERN", Symbol: "ERN", EnglishName: "Eritrean Nakfa", StandardScale: 2, MaxQuantityScale: 6},
	{Code: "ETB", Symbol: "ETB", EnglishName: "Ethiopian Birr", StandardScale: 2, MaxQuantityScale: 6},
	{Code: "EUR", Symbol: "€", EnglishName: "Euro", StandardScale: 2, MaxQuantityScale: 6},
	{Code: "FJD", Symbol: "$", EnglishName: "Fijian Dollar", StandardScale: 2, MaxQuantityScale: 6},
	{Code: "FKP", Symbol: "£", EnglishName: "Falkland Islands Pound", StandardScale: 2, MaxQuantityScale: 6},
	{Code: "GBP", Symbol: "£", EnglishName: "British Pound", StandardScale: 2, MaxQuantityScale: 6},
	{Code: "GEL", Symbol: "₾", EnglishName: "Georgian Lari", StandardScale: 2, MaxQuantityScale: 6},
	{Code: "GHS", Symbol: "GH₵", EnglishName: "Ghanaian Cedi", StandardScale: 2, MaxQuantityScale: 6},
	{Code: "GIP", Symbol: "£", EnglishName: "Gibraltar Pound", StandardScale: 2, MaxQuantityScale: 6},
	{Code: "GMD", Symbol: "GMD", EnglishName: "Gambian Dalasi", StandardScale: 2, MaxQuantityScale: 6},
	{Code: "GNF", Symbol: "FG", EnglishName: "Guinean Franc", StandardScale: 0, MaxQuantityScale: 6},
	{Code: "GTQ", Symbol: "Q", EnglishName: "Guatemalan Quetzal", StandardScale: 2, MaxQuantityScale: 6},
	{Code: "GYD", Symbol: "$", EnglishName: "Guyanaese Dollar", StandardScale: 2, MaxQuantityScale: 6},
	{Code: "HKD", Symbol: "$", EnglishName: "Hong Kong Dollar", StandardScale: 2, MaxQuantityScale: 6},
	{Code: "HNL", Symbol: "L", EnglishName: "Honduran Lempira", StandardScale: 2, MaxQuantityScale: 6},
	{Code: "HRK", Symbol: "kn", EnglishName: "Croatian Kuna", StandardScale: 2, MaxQuantityScale: 6},
	{Code: "HTG", Symbol: "HTG", EnglishName: "Haitian Gourde", StandardScale: 2, MaxQuantityScale: 6},
	{Code: "HUF", Symbol: "Ft", EnglishName: "Hungarian Forint", StandardScale: 0, MaxQuantityScale: 6},
	{Code: "IDR", Symbol: "Rp", EnglishName: "Indonesian Rupiah", StandardScale: 0, MaxQuantityScale: 6},
	{Code: "ILS", Symbol: "₪", EnglishName: "Israeli New Shekel", StandardScale: 2, MaxQuantityScale: 6},
	{Code: "INR", Symbol: "₹", EnglishName: "Indian Rupee", StandardScale: 2, MaxQuantityScale: 6},
	{Code: "IQD", Symbol: "IQD", EnglishName: "Iraqi Dinar", StandardScale: 0, MaxQuantityScale: 6},
	{Code: "IRR", Symbol: "IRR", EnglishName: "Iranian Rial", StandardScale: 0, MaxQuantityScale: 6},
	{Code: "ISK", Symbol: "kr", EnglishName: "Icelandic Króna", StandardScale: 0, MaxQuantityScale: 6},
	{Code: "JMD", Symbol: "$", EnglishName: "Jamaican Dollar", StandardScale: 2, MaxQuantityScale: 6},
	{Code: "JOD", Symbol: "JOD", EnglishName: "Jordanian Dinar", StandardScale: 3, MaxQuantityScale: 6},
	{Code: "JPY", Symbol: "¥", EnglishName: "Japanese Yen", StandardScale: 0, MaxQuantityScale: 6},
	{Code: "KES", Symbol: "KES", EnglishName: "Kenyan Shilling", StandardScale: 2, MaxQuantityScale: 6},
	{Code: "KGS", Symbol: "⃀", EnglishName: "Kyrgyz Som", StandardScale: 2, MaxQuantityScale: 6},
	{Code: "KHR", Symbol: "៛", EnglishName: "Cambodian Riel", StandardScale: 2, MaxQuantityScale: 6},
	{Code: "KMF", Symbol: "CF", EnglishName: "Comorian Franc", StandardScale: 0, MaxQuantityScale: 6},
	{Code: "KPW", Symbol: "₩", EnglishName: "North Korean Won", StandardScale: 0, MaxQuantityScale: 6},
	{Code: "KRW", Symbol: "₩", EnglishName: "South Korean Won", StandardScale: 0, MaxQuantityScale: 6},
	{Code: "KWD", Symbol: "KWD", EnglishName: "Kuwaiti Dinar", StandardScale: 3, MaxQuantityScale: 6},
	{Code: "KYD", Symbol: "$", EnglishName: "Cayman Islands Dollar", StandardScale: 2, MaxQuantityScale: 6},
	{Code: "KZT", Symbol: "₸", EnglishName: "Kazakhstani Tenge", StandardScale: 2, MaxQuantityScale: 6},
	{Code: "LAK", Symbol: "₭", EnglishName: "Laotian Kip", StandardScale: 0, MaxQuantityScale: 6},
	{Code: "LBP", Symbol: "L£", EnglishName: "Lebanese Pound", StandardScale: 0, MaxQuantityScale: 6},
	{Code: "LKR", Symbol: "Rs", EnglishName: "Sri Lankan Rupee", StandardScale: 2, MaxQuantityScale: 6},
	{Code: "LRD", Symbol: "$", EnglishName: "Liberian Dollar", StandardScale: 2, MaxQuantityScale: 6},
	{Code: "LSL", Symbol: "LSL", EnglishName: "Lesotho Loti", StandardScale: 2, MaxQuantityScale: 6},
	{Code: "LYD", Symbol: "LYD", EnglishName: "Libyan Dinar", StandardScale: 3, MaxQuantityScale: 6},
	{Code: "MAD", Symbol: "MAD", EnglishName: "Moroccan Dirham", StandardScale: 2, MaxQuantityScale: 6},
	{Code: "MDL", Symbol: "MDL", EnglishName: "Moldovan Leu", StandardScale: 2, MaxQuantityScale: 6},
	{Code: "MGA", Symbol: "Ar", EnglishName: "Malagasy Ariary", StandardScale: 0, MaxQuantityScale: 6},
	{Code: "MKD", Symbol: "MKD", EnglishName: "Macedonian Denar", StandardScale: 2, MaxQuantityScale: 6},
	{Code: "MMK", Symbol: "K", EnglishName: "Myanmar Kyat", StandardScale: 0, MaxQuantityScale: 6},
	{Code: "MNT", Symbol: "₮", EnglishName: "Mongolian Tugrik", StandardScale: 2, MaxQuantityScale: 6},
	{Code: "MOP", Symbol: "MOP", EnglishName: "Macanese Pataca", StandardScale: 2, MaxQuantityScale: 6},
	{Code: "MRU", Symbol: "MRU", EnglishName: "Mauritanian Ouguiya", StandardScale: 2, MaxQuantityScale: 6},
	{Code: "MUR", Symbol: "Rs", EnglishName: "Mauritian Rupee", StandardScale: 2, MaxQuantityScale: 6},
	{Code: "MVR", Symbol: "MVR", EnglishName: "Maldivian Rufiyaa", StandardScale: 2, MaxQuantityScale: 6},
	{Code: "MWK", Symbol: "MWK", EnglishName: "Malawian Kwacha", StandardScale: 2, MaxQuantityScale: 6},
	{Code: "MXN", Symbol: "$", EnglishName: "Mexican Peso", StandardScale: 2, MaxQuantityScale: 6},
	{Code: "MYR", Symbol: "RM", EnglishName: "Malaysian Ringgit", StandardScale: 2, MaxQuantityScale: 6},
	{Code: "MZN", Symbol: "MZN", EnglishName: "Mozambican Metical", StandardScale: 2, MaxQuantityScale: 6},
	{Code: "NAD", Symbol: "$", EnglishName: "Namibian Dollar", StandardScale: 2, MaxQuantityScale: 6},
	{Code: "NGN", Symbol: "₦", EnglishName: "Nigerian Naira", StandardScale: 2, MaxQuantityScale: 6},
	{Code: "NIO", Symbol: "C$", EnglishName: "Nicaraguan Córdoba", StandardScale: 2, MaxQuantityScale: 6},
	{Code: "NOK", Symbol: "kr", EnglishName: "Norwegian Krone", StandardScale: 2, MaxQuantityScale: 6},
	{Code: "NPR", Symbol: "Rs", EnglishName: "Nepalese Rupee", StandardScale: 2, MaxQuantityScale: 6},
	{Code: "NZD", Symbol: "$", EnglishName: "New Zealand Dollar", StandardScale: 2, MaxQuantityScale: 6},
	{Code: "OMR", Symbol: "OMR", EnglishName: "Omani Rial", StandardScale: 3, MaxQuantityScale: 6},
	{Code: "PAB", Symbol: "PAB", EnglishName: "Panamanian Balboa", StandardScale: 2, MaxQuantityScale: 6},
	{Code: "PEN", Symbol: "PEN", EnglishName: "Peruvian Sol", StandardScale: 2, MaxQuantityScale: 6},
	{Code: "PGK", Symbol: "PGK", EnglishName: "Papua New Guinean Kina", StandardScale: 2, MaxQuantityScale: 6},
	{Code: "PHP", Symbol: "₱", EnglishName: "Philippine Peso", StandardScale: 2, MaxQuantityScale: 6},
	{Code: "PKR", Symbol: "Rs", EnglishName: "Pakistani Rupee", StandardScale: 0, MaxQuantityScale: 6},
	{Code: "PLN", Symbol: "zł", EnglishName: "Polish Zloty", StandardScale: 2, MaxQuantityScale: 6},
	{Code: "PYG", Symbol: "₲", EnglishName: "Paraguayan Guarani", StandardScale: 0, MaxQuantityScale: 6},
	{Code: "QAR", Symbol: "QAR", EnglishName: "Qatari Riyal", StandardScale: 2, MaxQuantityScale: 6},
	{Code: "RON", Symbol: "lei", EnglishName: "Romanian Leu", StandardScale: 2, MaxQuantityScale: 6},
	{Code: "RSD", Symbol: "RSD", EnglishName: "Serbian Dinar", StandardScale: 2, MaxQuantityScale: 6},
	{Code: "RUB", Symbol: "₽", EnglishName: "Russian Ruble", StandardScale: 2, MaxQuantityScale: 6},
	{Code: "RWF", Symbol: "RF", EnglishName: "Rwandan Franc", StandardScale: 0, MaxQuantityScale: 6},
	{Code: "SAR", Symbol: "SAR", EnglishName: "Saudi Riyal", StandardScale: 2, MaxQuantityScale: 6},
	{Code: "SBD", Symbol: "$", EnglishName: "Solomon Islands Dollar", StandardScale: 2, MaxQuantityScale: 6},
	{Code: "SCR", Symbol: "SCR", EnglishName: "Seychellois Rupee", StandardScale: 2, MaxQuantityScale: 6},
	{Code: "SDG", Symbol: "SDG", EnglishName: "Sudanese Pound", StandardScale: 2, MaxQuantityScale: 6},
	{Code: "SEK", Symbol: "kr", EnglishName: "Swedish Krona", StandardScale: 2, MaxQuantityScale: 6},
	{Code: "SGD", Symbol: "$", EnglishName: "Singapore Dollar", StandardScale: 2, MaxQuantityScale: 6},
	{Code: "SHP", Symbol: "£", EnglishName: "St. Helena Pound", StandardScale: 2, MaxQuantityScale: 6},
	{Code: "SLE", Symbol: "SLE", EnglishName: "Sierra Leonean Leone", StandardScale: 2, MaxQuantityScale: 6},
	{Code: "SLL", Symbol: "SLL", EnglishName: "Sierra Leonean Leone (1964—2022)", StandardScale: 0, MaxQuantityScale: 6},
	{Code: "SOS", Symbol: "SOS", EnglishName: "Somali Shilling", StandardScale: 0, MaxQuantityScale: 6},
	{Code: "SRD", Symbol: "$", EnglishName: "Surinamese Dollar", StandardScale: 2, MaxQuantityScale: 6},
	{Code: "SSP", Symbol: "£", EnglishName: "South Sudanese Pound", StandardScale: 2, MaxQuantityScale: 6},
	{Code: "STN", Symbol: "Db", EnglishName: "São Tomé & Príncipe Dobra", StandardScale: 2, MaxQuantityScale: 6},
	{Code: "SVC", Symbol: "SVC", EnglishName: "Salvadoran Colón", StandardScale: 2, MaxQuantityScale: 6},
	{Code: "SYP", Symbol: "£", EnglishName: "Syrian Pound", StandardScale: 0, MaxQuantityScale: 6},
	{Code: "SZL", Symbol: "SZL", EnglishName: "Swazi Lilangeni", StandardScale: 2, MaxQuantityScale: 6},
	{Code: "THB", Symbol: "฿", EnglishName: "Thai Baht", StandardScale: 2, MaxQuantityScale: 6},
	{Code: "TJS", Symbol: "TJS", EnglishName: "Tajikistani Somoni", StandardScale: 2, MaxQuantityScale: 6},
	{Code: "TMT", Symbol: "TMT", EnglishName: "Turkmenistani Manat", StandardScale: 2, MaxQuantityScale: 6},
	{Code: "TND", Symbol: "TND", EnglishName: "Tunisian Dinar", StandardScale: 3, MaxQuantityScale: 6},
	{Code: "TOP", Symbol: "T$", EnglishName: "Tongan Paʻanga", StandardScale: 2, MaxQuantityScale: 6},
	{Code: "TRY", Symbol: "₺", EnglishName: "Turkish Lira", StandardScale: 2, MaxQuantityScale: 6},
	{Code: "TTD", Symbol: "$", EnglishName: "Trinidad & Tobago Dollar", StandardScale: 2, MaxQuantityScale: 6},
	{Code: "TWD", Symbol: "$", EnglishName: "New Taiwan Dollar", StandardScale: 2, MaxQuantityScale: 6},
	{Code: "TZS", Symbol: "TZS", EnglishName: "Tanzanian Shilling", StandardScale: 2, MaxQuantityScale: 6},
	{Code: "UAH", Symbol: "₴", EnglishName: "Ukrainian Hryvnia", StandardScale: 2, MaxQuantityScale: 6},
	{Code: "UGX", Symbol: "UGX", EnglishName: "Ugandan Shilling", StandardScale: 0, MaxQuantityScale: 6},
	{Code: "USD", Symbol: "$", EnglishName: "US Dollar", StandardScale: 2, MaxQuantityScale: 6},
	{Code: "UYU", Symbol: "$", EnglishName: "Uruguayan Peso", StandardScale: 2, MaxQuantityScale: 6},
	{Code: "UZS", Symbol: "UZS", EnglishName: "Uzbekistani Som", StandardScale: 2, MaxQuantityScale: 6},
	{Code: "VES", Symbol: "VES", EnglishName: "Venezuelan Bolívar", StandardScale: 2, MaxQuantityScale: 6},
	{Code: "VND", Symbol: "₫", EnglishName: "Vietnamese Dong", StandardScale: 0, MaxQuantityScale: 6},
	{Code: "VUV", Symbol: "VUV", EnglishName: "Vanuatu Vatu", StandardScale: 0, MaxQuantityScale: 6},
	{Code: "WST", Symbol: "WST", EnglishName: "Samoan Tala", StandardScale: 2, MaxQuantityScale: 6},
	{Code: "XAF", Symbol: "FCFA", EnglishName: "Central African CFA Franc", StandardScale: 0, MaxQuantityScale: 6},
	{Code: "XCD", Symbol: "$", EnglishName: "East Caribbean Dollar", StandardScale: 2, MaxQuantityScale: 6},
	{Code: "XCG", Symbol: "Cg.", EnglishName: "Caribbean guilder", StandardScale: 2, MaxQuantityScale: 6},
	{Code: "XDR", Symbol: "XDR", EnglishName: "Special Drawing Rights", StandardScale: 2, MaxQuantityScale: 6},
	{Code: "XOF", Symbol: "F CFA", EnglishName: "West African CFA Franc", StandardScale: 0, MaxQuantityScale: 6},
	{Code: "XPF", Symbol: "CFPF", EnglishName: "CFP Franc", StandardScale: 0, MaxQuantityScale: 6},
	{Code: "XSU", Symbol: "XSU", EnglishName: "Sucre", StandardScale: 2, MaxQuantityScale: 6},
	{Code: "YER", Symbol: "YER", EnglishName: "Yemeni Rial", StandardScale: 0, MaxQuantityScale: 6},
	{Code: "ZAR", Symbol: "R", EnglishName: "South African Rand", StandardScale: 2, MaxQuantityScale: 6},
	{Code: "ZMW", Symbol: "ZK", EnglishName: "Zambian Kwacha", StandardScale: 2, MaxQuantityScale: 6},
	{Code: "ZWG", Symbol: "ZWG", EnglishName: "Zimbabwean Gold", StandardScale: 2, MaxQuantityScale: 6},
	{Code: "ZWL", Symbol: "ZWL", EnglishName: "Zimbabwean Dollar (2009–2024)", StandardScale: 2, MaxQuantityScale: 6},
}
